### ISSUE TITLE
Original Cache Settings Overrided

### ISSUE THREAD

**Issue by jiefangxuanyan** [vinyll/django-imagefit#10] opened 2016-06-22 02:40 UTC
The code in conf.py is overriding original cache settings of Django, causing the 'default' value of cache lost.
`settings.CACHES = ...`

**Comment by laurivosandi** [comment] 2016-07-02 20:17
Hi, I can confirm the issue. This also seems to be fixed in many of the forks of this repo.

**Comment by vinyll** [comment] 2016-07-03 13:47
Hey,
It should be fixed in https://github.com/vinyll/django-imagefit/commit/721fe036c403d140a88abb847f6e01908d1e6e95
Please reopen if it's not the case

**Closed by vinyll** 2016-07-03 13:47 UTC
